#ifndef FLAKELIB_VOLUME_VON_NEUMANN_SIZE_T_NEIGHBORS_CL_INCLUDED
#define FLAKELIB_VOLUME_VON_NEUMANN_SIZE_T_NEIGHBORS_CL_INCLUDED

#include <flakelib/volume/von_neumann/define_neighbors.cl>

FLAKELIB_VOLUME_VON_NEUMANN_DEFINE_NEIGHBORS(
	size_t,
	flakelib_volume_von_neumann_size_t_neighbors);

#endif
