#ifndef FLAKELIB_VOLUME_VON_NEUMANN_FLOAT4_NEIGHBORS_CL_INCLUDED
#define FLAKELIB_VOLUME_VON_NEUMANN_FLOAT4_NEIGHBORS_CL_INCLUDED

#include <flakelib/volume/von_neumann/define_neighbors.cl>

FLAKELIB_VOLUME_VON_NEUMANN_DEFINE_NEIGHBORS(
	float4,
	flakelib_volume_von_neumann_float4_neighbors);

#endif
