#ifndef FLAKELIB_VOLUME_VON_NEUMANN_SUM_CL_INCLUDED
#define FLAKELIB_VOLUME_VON_NEUMANN_SUM_CL_INCLUDED

#include <flakelib/volume/von_neumann/fold.cl>

#define FLAKELIB_VOLUME_VON_NEUMANN_SUM_ADD_OPERATION(a,b)\
	(a)+(b)

#define FLAKELIB_VOLUME_VON_NEUMANN_SUM(v)\
	FLAKELIB_VOLUME_VON_NEUMANN_FOLD(\
		FLAKELIB_VOLUME_VON_NEUMANN_SUM_ADD_OPERATION,\
		v)

#endif
